args:
  data_path: ./data/raw/sample_10000.csv
  lemmatize: true
  lowercase: false
  model_dir: ./models/
  remove_punctuation: false
  remove_stopwords: false
  save_model: false
  save_validation: false
  validation_dir: ./runs/
model: tfidf
